//
// Created by Diaz, Diego on 21.5.2025.
//
#include<iostream>
#include "../bwt_io.h"
#include<thread>
#include "../utils.h"
#include "custom_wt_rlmn.hpp"

typedef std::tuple<uint64_t, uint64_t, uint64_t, bool> sa_samp_type;
typedef sdsl::custom_wt_rlmn<> index_type;

void compute_samples(size_t n_threads, index_type& bwt, std::string& output_file) {

    std::vector<std::vector<sa_samp_type>> thread_sa_samples(n_threads);
    auto lambda_worker = [&](size_t start, size_t end, size_t t) -> void {

        // I am exploiting the fact that the strings in the BCR BWT
        // can be decoded in text order.
        for(size_t i=start;i<=end;i++){

            size_t bwt_pos = i;
            uint64_t len = 1;
            size_t n_insertions=0;

            while(true){
                if(bwt.is_run_head(bwt_pos)){
                    thread_sa_samples[t].emplace_back(i, len, bwt.pos2run(bwt_pos), false);
                    n_insertions++;
                }

                if(bwt.is_run_tail(bwt_pos)){
                    thread_sa_samples[t].emplace_back(i, len, bwt.pos2run(bwt_pos), true);
                    n_insertions++;
                }

                auto res = bwt.lf(bwt_pos);
                if(res.first==bwt.sep_sym()){
                    assert(res.second<bwt.n_strings());
                    break;
                }
                len++;
                bwt_pos = res.second;
            }
            for(size_t j=0, k=thread_sa_samples[t].size()-n_insertions;j<n_insertions;j++,k++){
                std::get<1>(thread_sa_samples[t][k]) = len-std::get<1>(thread_sa_samples[t][k]);
            }
        }
    };

    size_t n_strings = bwt.n_strings();
    size_t strings_per_thread = INT_CEIL((n_strings), n_threads);
    std::vector<std::thread> working_threads;
    for (size_t i = 0; i < n_threads; i++) {
        size_t start = strings_per_thread * i;
        size_t end = std::min<size_t>(strings_per_thread * (i + 1), n_strings)-1;

        working_threads.emplace_back(lambda_worker, start, end, i);
        if(end == (n_strings-1)) break;
    }

    std::cout<<"Computing the SA samples from the BWT using "<<working_threads.size()<<" working threads"<<std::endl;
    for (auto &working_thread: working_threads) {
        working_thread.join();
    }

    std::vector<sa_samp_type> sa_samples;
    for (auto& vec : thread_sa_samples) {
        sa_samples.insert(sa_samples.end(),
                          std::make_move_iterator(vec.begin()),
                          std::make_move_iterator(vec.end()));
    }

    std::cout<<"Sorting the samples"<<std::endl;
    std::sort(sa_samples.begin(), sa_samples.end(), [](const auto& a, const auto& b) {
        uint64_t run_a = std::get<2>(a);
        uint64_t run_b = std::get<2>(b);
        if(run_a!=run_b){
            return run_a<run_b;
        }
        return std::get<3>(a) < std::get<3>(b);
    });

    assert((sa_samples.size()/2)==bwt.n_runs());
    sdsl::int_vector_buffer<0> output;

    std::ofstream ofs(output_file, std::ios::binary);
    auto *buffer = (uint64_t *) malloc(sizeof(uint64_t)*4096);
    size_t b_pos=0;

    for(auto & sa_sample : sa_samples){
        buffer[b_pos++] = std::get<0>(sa_sample);
        buffer[b_pos++] = std::get<1>(sa_sample);
        if(b_pos==4096){
            ofs.write((char *)buffer, 4096*sizeof(uint64_t));
            b_pos=0;
        }
        //std::cout<<"(str:"<<std::get<0>(sa_sample)<<":"<<std::get<1>(sa_sample)<<") run:"<<std::get<2>(sa_sample)<<" head/tail:"<<std::get<3>(sa_sample)<<std::endl;
    }

    if(b_pos!=0){
        ofs.write((char *)buffer, std::streamsize(b_pos*sizeof(uint64_t)));
    }
    ofs.close();
    free(buffer);
}

int main(int argc, char** argv) {
    if(argc!=4){
        std::cout<<"usage: ./get_r_sa_samples file.rlbwt n_threads output_file\n\n"
                    "file.rlbwt: the BCR BWT file generated by grlBWT\n"
                    "n_threads: number of threads to compute the samples\n"
                    "output_file: file where the samples will be stored"<< std::endl;
        exit(0);
    }
    errno = 0;
    std::string input_file = std::string(argv[1]);
    char *endptr;
    uint64_t n_threads = strtol(argv[2], &endptr, 10);
    if (*endptr != '\0') {
        fprintf(stderr, "Invalid number of threads: %s\n", argv[1]);
        return 1;
    }
    std::string output_file = std::string(argv[3]);
    std::cout<<"Building the RLBWT ..."<<std::endl;
    index_type bwt(input_file);
    std::cout<<"Input file:"<<input_file<<" has "<<bwt.n_strings()<<" strings and "<<bwt.n_runs()<<" BWT runs"<<std::endl;
    compute_samples(n_threads, bwt, output_file);
    std::cout<<"SA samples were stored in "<<output_file<<std::endl;
}
