//
// Created by Diaz, Diego on 21.5.2025.
//
#include<iostream>
#include "../bwt_io.h"
#include<thread>
#include "../utils.h"
#include "custom_wt_rlmn.hpp"

typedef std::tuple<uint64_t, uint64_t, uint64_t, bool> sa_samp_type;
typedef sdsl::custom_wt_rlmn<> index_type;

void compute_samples(size_t n_threads, index_type& bwt) {



    std::vector<std::vector<sa_samp_type>> thread_sa_samples(n_threads);
    auto lambda_worker = [&](size_t start, size_t end, size_t t) -> void {

        // I am exploiting the fact that the strings in the BCR BWT
        // can be decoded in text order.
        for(size_t i=start;i<=end;i++){

            size_t bwt_pos = i;
            uint64_t len = 0;
            size_t n_insertions=0;

            while(true){
                if(bwt.is_run_head(bwt_pos)){
                    thread_sa_samples[t].emplace_back(i, len, bwt.pos2run(bwt_pos), false);
                    n_insertions++;
                }

                if(bwt.is_run_tail(bwt_pos)){
                    thread_sa_samples[t].emplace_back(i, len, bwt.pos2run(bwt_pos), true);
                    n_insertions++;
                }

                auto res = bwt.lf(bwt_pos);
                if(res.first==0){
                    assert(res.first<bwt.C_vec[1]);
                    break;
                }
                bwt_pos = res.second;
                len++;

                if(len % 1000000==0){
                    std::cout<<len<<std::endl;
                }
            }

            for(size_t j=0, k=thread_sa_samples[t].size()-n_insertions;j<n_insertions;j++,k++){
                std::get<1>(thread_sa_samples[t][k]) = len-j;
            }
        }
        std::sort(thread_sa_samples[t].begin(), thread_sa_samples[t].end());
    };

    std::cout<<"    Computing the SA samples from the BWT"<<std::flush;
    //auto t_start = std::chrono::steady_clock::now();
    //{
        size_t n_strings = bwt.n_strings();
        size_t strings_per_thread = INT_CEIL((n_strings), n_threads);
        std::vector<std::thread> working_threads;
        for (size_t i = 0; i < n_threads; i++) {
            size_t start = strings_per_thread * i;
            size_t end = std::min<size_t>(strings_per_thread * (i + 1), n_strings)-1;

            working_threads.emplace_back(lambda_worker, start, end, i);
            if(end == (n_strings-1)) break;
        }
        for (auto &working_thread: working_threads) {
            working_thread.join();
        }
    //}
    //auto t_end = std::chrono::steady_clock::now();
    //report_time(t_start, t_end, 2);
}

int main(int argc, char** argv) {
    if(argc!=2){
        std::cout<<"usage: ./get_r_sa_samples file.rlbwt n_threads sep_sym\n\n"
                    "file.rlbwt: the BCR BWT file generated by grlBWT\n"<< std::endl;
        exit(0);
    }
    errno = 0;
    std::string input_file = std::string(argv[1]);
    size_t n_threads=1;

    index_type bwt(input_file);

    compute_samples(n_threads, bwt);
}
