//
// Created by Diaz, Diego on 21.5.2025.
//
#include<iostream>
#include <thread>
#include "../include/bwt_io.h"
#include "../include/utils.h"
#include "../test_suite/custom_wt_rlmn.hpp"

enum run_annot_t{
    NONE=0,
    HEAD=1,
    TAIL=2,
};

struct sa_val_type{
    uint32_t str=0;
    uint32_t sa_val=0;
    uint32_t inv_sa_val=0;

    sa_val_type(uint32_t str_, uint32_t sa_val_, uint32_t inv_sa_val_): str(str_),
                                                                        sa_val(sa_val_),
                                                                        inv_sa_val(inv_sa_val_){}
};

typedef sdsl::custom_wt_rlmn<> index_type;

void compute_samples(size_t n_threads, index_type& bwt, std::string& sa_file, std::string& str_ranges_file) {

    std::vector<uint64_t> str_lens(bwt.n_strings()+1);
    std::vector<std::vector<sa_val_type>> thread_sa_samples(n_threads);

    auto lambda_worker = [&](const size_t start, const size_t end, size_t t) -> void {

        // I am exploiting the fact that the strings in the BCR BWT can be decoded in text order.
        std::vector<sa_val_type> tmp;

        for(size_t i=start;i<=end;i++){

            size_t bwt_pos = i;
            uint64_t len = 1;

            while(true) {

                tmp.emplace_back(i, len, bwt_pos);
                auto res = bwt.lf(bwt_pos);

                if(res.first==bwt.sep_sym()){
                    assert(res.second<bwt.n_strings());
                    str_lens[i] = len;
                    break;
                }
                len++;
                bwt_pos = res.second;
            }

            std::reverse(tmp.begin(), tmp.end());
            for(auto &samp : tmp) {
                samp.sa_val = len-samp.sa_val;
                thread_sa_samples[t].push_back(samp);
            }
            tmp.clear();
        }
    };

    size_t n_strings = bwt.n_strings();
    size_t strings_per_thread = INT_CEIL((n_strings), n_threads);
    std::vector<std::thread> working_threads;
    for (size_t i = 0; i < n_threads; i++) {
        size_t start = strings_per_thread * i;
        size_t end = std::min<size_t>(strings_per_thread * (i + 1), n_strings)-1;

        working_threads.emplace_back(lambda_worker, start, end, i);
        if(end == (n_strings-1)) break;
    }

    std::cout<<"Computing the SA samples from the BWT using "<<working_threads.size()<<" working threads"<<std::endl;
    for (auto &working_thread: working_threads) {
        working_thread.join();
    }

    std::vector<sa_val_type> sa_samples;
    for (auto& vec : thread_sa_samples) {
        sa_samples.insert(sa_samples.end(),
                          std::make_move_iterator(vec.begin()),
                          std::make_move_iterator(vec.end()));
    }

    size_t acc=0, tmp;
    for(auto &len : str_lens){
        tmp = len;
        len = acc;
        acc+=tmp;
    }
    str_lens[n_strings] = acc;

    for(auto &elm : sa_samples){
        elm.sa_val+=str_lens[elm.str];
    }

    std::cout<<"Sorting the samples"<<std::endl;
    std::sort(sa_samples.begin(), sa_samples.end(), [](const sa_val_type& a, const sa_val_type& b) {
        return a.inv_sa_val<b.inv_sa_val;
    });

    off_t buff_size = sizeof(uint32_t)*4096;
    auto *buffer = static_cast<uint32_t *>(malloc(buff_size));
    std::ofstream ofs(sa_file, std::ios::binary);
    off_t b_pos=0;

    size_t k=0;
    for(auto & sa_sample : sa_samples){
        buffer[b_pos] = sa_sample.sa_val;
        b_pos++;
        if(b_pos==4096){
            ofs.write((char *)buffer, buff_size);
            b_pos=0;
        }
        k++;
    }
    if(b_pos!=0){
        buff_size = off_t(b_pos*sizeof(uint32_t));
        ofs.write((char *)buffer, buff_size);
    }
    ofs.close();
    free(buffer);

    std::ofstream ofs2(str_ranges_file, std::ios::binary);
    ofs2.write((char *)str_lens.data(), off_t(sizeof(uint64_t)*str_lens.size()));
    assert(sa_samples.size()==bwt.size());
    std::cout<<"Total number of SA values: "<<sa_samples.size()<<std::endl;
}

int main(int argc, char** argv) {
    if(argc!=4){
        std::cout<<"usage: ./get_r_sa_samples file.rlbwt n_threads output_file\n\n"
                    "file.rlbwt: the BCR BWT file generated by grlBWT\n"
                    "n_threads: number of threads to compute the samples\n"
                    "output_file: file where the samples will be stored"<< std::endl;
        exit(0);
    }
    errno = 0;
    std::string input_file = std::string(argv[1]);
    char *endptr;
    uint64_t n_threads = strtol(argv[2], &endptr, 10);
    if (*endptr != '\0') {
        fprintf(stderr, "Invalid number of threads: %s\n", argv[1]);
        return 1;
    }
    std::string sa_file = std::string(argv[3])+".sa";
    std::string str_ranges_file = std::string(argv[3])+".str_ranges";
    std::cout<<"Building the RLBWT ..."<<std::endl;
    index_type bwt(input_file);
    std::cout<<"Input file:"<<input_file<<" has "<<bwt.n_strings()<<" strings and "<<bwt.n_runs()<<" BWT runs"<<std::endl;
    compute_samples(n_threads, bwt, sa_file, str_ranges_file);
    std::cout<<"SA samples were stored in "<<sa_file<<std::endl;
    std::cout<<"The ranges of the strings in the text were stored in "<<str_ranges_file<<std::endl;
}
